-- Ledgerly completion migration. Safe additive changes only.
alter table public.expenses add column if not exists deleted_at timestamptz;
alter table public.expenses add column if not exists updated_at timestamptz not null default now();
alter table public.expenses add column if not exists updated_by uuid;
alter table public.categories add column if not exists is_active boolean not null default true;
alter table public.recurring_expenses add column if not exists frequency text not null default 'monthly';
alter table public.recurring_expenses add column if not exists start_date date;
alter table public.recurring_expenses add column if not exists end_date date;
alter table public.recurring_expenses add column if not exists auto_create boolean not null default false;
alter table public.recurring_expenses add column if not exists last_generated_date date;
alter table public.recurring_expenses add column if not exists responsibility jsonb;
alter table public.emis add column if not exists lender text;
alter table public.emis add column if not exists interest_rate numeric;
alter table public.emis add column if not exists start_date date;
alter table public.emis add column if not exists total_installments integer;
alter table public.emis add column if not exists notes text;
create table if not exists public.family_transfers(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,from_member_id uuid not null references public.family_members(id),to_member_id uuid not null references public.family_members(id),amount numeric(14,2) not null check(amount>0),date date not null default current_date,notes text,created_at timestamptz not null default now());
create table if not exists public.family_loans(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,name text not null,principal numeric(14,2) not null check(principal>0),outstanding numeric(14,2),from_member_id uuid not null references public.family_members(id),to_member_id uuid not null references public.family_members(id),due_date date,status text not null default 'open',notes text,created_at timestamptz not null default now());
alter table public.family_transfers enable row level security;
alter table public.family_loans enable row level security;
create index if not exists family_transfers_family_id_idx on public.family_transfers(family_id);
create index if not exists family_loans_family_id_idx on public.family_loans(family_id);
create index if not exists expenses_family_date_idx on public.expenses(family_id,expense_date);
create index if not exists expenses_deleted_at_idx on public.expenses(deleted_at);
drop policy if exists family_transfers_select on public.family_transfers;
drop policy if exists family_transfers_insert on public.family_transfers;
drop policy if exists family_loans_select on public.family_loans;
drop policy if exists family_loans_insert on public.family_loans;
create policy family_transfers_select on public.family_transfers for select to authenticated using (public.is_family_member(family_id));
create policy family_transfers_insert on public.family_transfers for insert to authenticated with check (public.is_family_member(family_id));
create policy family_loans_select on public.family_loans for select to authenticated using (public.is_family_member(family_id));
create policy family_loans_insert on public.family_loans for insert to authenticated with check (public.is_family_member(family_id));
