'use client';
import { useEffect,useState } from 'react';
import { supabase } from '../../lib/supabaseClient';
import { money } from '../../lib/money';
const today=()=>new Date().toISOString().slice(0,10);

type Funding='member'|'household';
export default function TransactionsPage(){
 const [session,setSession]=useState<any>(null),[family,setFamily]=useState<any>(null),[members,setMembers]=useState<any[]>([]),[categories,setCategories]=useState<any[]>([]),[type,setType]=useState<'expense'|'income'>('expense'),[loading,setLoading]=useState(true),[msg,setMsg]=useState('');
 const [expense,setExpense]=useState({description:'',amount:'',date:today(),payer:'',fundingSource:'member' as Funding,category:'',responsible:''});
 const [income,setIncome]=useState({description:'Salary',amount:'',date:today(),source:'household',category:''});
 useEffect(()=>{const q=new URLSearchParams(location.search);setType(q.get('type')==='income'?'income':'expense');supabase.auth.getSession().then(async({data})=>{setSession(data.session);if(data.session)await load();else setLoading(false);});},[]);
 async function load(){
  setLoading(true);const {data:fs,error}=await supabase.from('families').select('*').order('created_at',{ascending:true});if(error){setMsg(error.message);setLoading(false);return;}
  const saved=localStorage.getItem('ledgerly_family_id');const f=(fs||[]).find((x:any)=>x.id===saved)||(fs||[])[0];if(!f){setMsg('No family selected. Return to Ledgerly and choose a family.');setLoading(false);return;}setFamily(f);
  const [m,c]=await Promise.all([supabase.from('family_members').select('*').eq('family_id',f.id).eq('is_active',true).order('created_at'),supabase.from('categories').select('*').eq('family_id',f.id).order('kind').order('name')]);
  setMembers(m.data||[]);setCategories(c.data||[]);const first=(m.data||[])[0];setExpense(x=>({...x,payer:x.payer||first?.id||'',responsible:x.responsible||first?.id||'',category:x.category||(c.data||[]).find((z:any)=>z.kind==='expense')?.id||''}));setIncome(x=>({...x,category:x.category||(c.data||[]).find((z:any)=>z.kind==='income')?.id||''}));setLoading(false);
 }
 async function saveIncome(e:any){e.preventDefault();if(!family||!session||!income.amount){setMsg('Enter an income amount.');return;}const amount=Number(income.amount);if(!Number.isFinite(amount)||amount<=0){setMsg('Amount must be greater than ₹0.');return;}setLoading(true);const r=await supabase.from('incomes').insert({family_id:family.id,member_id:income.source==='household'?null:income.source,category_id:income.category||null,description:income.description||'Income',amount,income_date:income.date,created_by:session.user.id});if(r.error){setMsg(r.error.message);setLoading(false);return;}location.href='/';}
 async function saveExpense(e:any){e.preventDefault();if(!family||!session||!expense.description||!expense.amount||!expense.payer){setMsg('Complete description, amount and payer.');return;}const amount=Number(expense.amount);if(!Number.isFinite(amount)||amount<=0){setMsg('Amount must be greater than ₹0.');return;}const responsible=expense.responsible||expense.payer;setLoading(true);
  const r=await supabase.from('expenses').insert({family_id:family.id,category_id:expense.category||null,description:expense.description.trim(),amount,expense_date:expense.date,expense_type:'variable',payment_method:null,notes:expense.fundingSource==='household'?'Household-funded expense':null,split_mode:'single',funding_source:expense.fundingSource,recorded_payer_id:expense.payer,created_by:session.user.id}).select().single();
  if(r.error){setMsg(r.error.message);setLoading(false);return;}const ar=await supabase.from('expense_allocations').insert({expense_id:r.data.id,member_id:responsible,amount});if(ar.error){setMsg(ar.error.message);setLoading(false);return;}
  const pr=await supabase.from('expense_payers').insert({expense_id:r.data.id,member_id:expense.payer,amount});if(pr.error){setMsg(pr.error.message);setLoading(false);return;}location.href='/';
 }
 if(!session&&!loading)return <main className="auth"><div className="authCard"><h1>Sign in required</h1><p>Please sign in to add a transaction.</p><button className="btn primary full" onClick={()=>location.href='/'}>Back to Ledgerly</button></div></main>;
 return <main className="auth" style={{alignItems:'start',paddingTop:28}}><div className="authCard wide" style={{maxWidth:760}}>
  <div className="pageTitle"><div><span className="eyebrow">Ledgerly</span><h1>Add {type==='income'?'income':'expense'}</h1><p>{family?.name||'Family'} · shared money tracking</p></div><button className="linkBtn" onClick={()=>location.href='/'}>Back</button></div>
  <div className="seg"><button type="button" className={type==='expense'?'on':''} onClick={()=>{setType('expense');history.replaceState({},'','/transactions?type=expense')}}>Expense</button><button type="button" className={type==='income'?'on':''} onClick={()=>{setType('income');history.replaceState({},'','/transactions?type=income')}}>Income</button></div>
  {msg&&<div className="notice">{msg}</div>}
  {type==='income'?<form className="expenseForm" onSubmit={saveIncome}><label>Description<input value={income.description} onChange={e=>setIncome({...income,description:e.target.value})}/></label><label>Amount<input required type="number" min="0.01" step="0.01" value={income.amount} onChange={e=>setIncome({...income,amount:e.target.value})}/></label><label>Income source<select value={income.source} onChange={e=>setIncome({...income,source:e.target.value})}><option value="household">Household / Home income</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Category<select value={income.category} onChange={e=>setIncome({...income,category:e.target.value})}>{categories.filter(c=>c.kind==='income'&&c.is_active!==false).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Date<input type="date" value={income.date} onChange={e=>setIncome({...income,date:e.target.value})}/></label><div className="formFooter span2"><button className="btn primary" disabled={loading}>{loading?'Saving…':'Add income'}</button></div></form>:<form className="expenseForm" onSubmit={saveExpense}><label className="span2">What was it for?<input required value={expense.description} onChange={e=>setExpense({...expense,description:e.target.value})} placeholder="Groceries, electricity, dinner…"/></label><label>Amount<input required type="number" min="0.01" step="0.01" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/></label><label>Paid from<select value={expense.fundingSource} onChange={e=>setExpense({...expense,fundingSource:e.target.value as Funding})}><option value="member">Member's money</option><option value="household">Household / Home money</option></select></label><label>{expense.fundingSource==='household'?'Recorded payer':'Payer'}<select value={expense.payer} onChange={e=>setExpense({...expense,payer:e.target.value})}>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Responsibility<select value={expense.responsible} onChange={e=>setExpense({...expense,responsible:e.target.value})}>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Date<input type="date" value={expense.date} onChange={e=>setExpense({...expense,date:e.target.value})}/></label><label className="span2">Category<select value={expense.category} onChange={e=>setExpense({...expense,category:e.target.value})}>{categories.filter(c=>c.kind==='expense'&&c.is_active!==false).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="formFooter span2"><span className="muted">Household-funded expenses do not create a personal receivable for the recorded payer.</span><button className="btn primary" disabled={loading}>{loading?'Saving…':'Save expense'}</button></div></form>}
 </div></main>;
}
