'use client';
import { useEffect,useState } from 'react';
import { createClient } from '@supabase/supabase-js';
const supabase=createClient('https://gkkrsadkjehmeobradxs.supabase.co','sb_publishable_AHlcX2dM-2NTJ9LKOyYplg_CH4qSDmj');
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(n)||0);
const today=()=>new Date().toISOString().slice(0,10); const month=(d:string)=>d?.slice(0,7)||'';
const TYPES=[['variable','Daily / Variable'],['fixed','Fixed / Recurring'],['emi','EMI / Loan']];
const PAYMENTS=['UPI','Cash','Bank Transfer','Debit Card','Credit Card','Wallet','Other'];
function splitEqual(amount:number,ids:string[]){const base=Math.floor(amount*100/ids.length)/100;return ids.map((id,i)=>({member_id:id,amount:i===ids.length-1?Number((amount-base*(ids.length-1)).toFixed(2)):base}));}
function balances(expenses:any[],settlements:any[],members:any[]){const m:Record<string,number>={};members.forEach(x=>m[x.id]=0);expenses.filter(e=>!e.deleted_at).forEach(e=>{(e.expense_payers||[]).forEach((p:any)=>m[p.member_id]=(m[p.member_id]||0)+Number(p.amount));(e.expense_allocations||[]).forEach((a:any)=>m[a.member_id]=(m[a.member_id]||0)-Number(a.amount));});settlements.filter(s=>s.status!=='reversed').forEach(s=>{const a=Number(s.paid_amount||s.amount||0);m[s.from_member_id]=(m[s.from_member_id]||0)+a;m[s.to_member_id]=(m[s.to_member_id]||0)-a});return members.map(x=>({...x,balance:Number((m[x.id]||0).toFixed(2))}));}
function settleSuggestions(bs:any[]){const d=bs.filter(x=>x.balance<-.005).map(x=>({...x,amt:-x.balance})).sort((a,b)=>b.amt-a.amt);const c=bs.filter(x=>x.balance>.005).map(x=>({...x,amt:x.balance})).sort((a,b)=>b.amt-a.amt);const out:any[]=[];let i=0,j=0;while(i<d.length&&j<c.length){const n=Math.min(d[i].amt,c[j].amt);out.push({from:d[i].id,to:c[j].id,fromName:d[i].name,toName:c[j].name,amount:Number(n.toFixed(2))});d[i].amt-=n;c[j].amt-=n;if(d[i].amt<.005)i++;if(c[j].amt<.005)j++;}return out;}
export default function Home(){
 const [session,setSession]=useState<any>();const [family,setFamily]=useState<any>();const [families,setFamilies]=useState<any[]>([]);const [members,setMembers]=useState<any[]>([]);const [cats,setCats]=useState<any[]>([]);const [expenses,setExpenses]=useState<any[]>([]);const [income,setIncome]=useState<any[]>([]);const [settlements,setSettlements]=useState<any[]>([]);const [screen,setScreen]=useState('home');const [email,setEmail]=useState('');const [notice,setNotice]=useState('');const [familyMode,setFamilyMode]=useState('choose');const [familyForm,setFamilyForm]=useState({name:'',pin:'',code:'',memberName:''});const [busy,setBusy]=useState(false);const [dark,setDark]=useState(false);
 const [form,setForm]=useState<any>({description:'',amount:'',date:today(),category:'',payer:'',type:'variable',payment:'UPI',members:[] as string[],split:'single'});const [search,setSearch]=useState('');const [filter,setFilter]=useState(month(today()));
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)loadFamilies()},[session]);useEffect(()=>{if(family)loadFamily(family.id)},[family?.id]);useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);
 async function loadFamilies(){const {data,error}=await supabase.from('families').select('*').order('created_at');if(error)return setNotice(error.message);setFamilies(data||[]);const saved=localStorage.getItem('ledgerly_family_id');const f=(data||[]).find(x=>x.id===saved)||(data||[])[0];if(f)setFamily(f)}
 async function loadFamily(id:string){setBusy(true);const [m,c,e,i,s]=await Promise.all([supabase.from('family_members').select('*').eq('family_id',id).order('created_at'),supabase.from('categories').select('*').eq('family_id',id).order('kind').order('name'),supabase.from('expenses').select('*,expense_payers(member_id,amount),expense_allocations(member_id,amount),categories(name)').eq('family_id',id).order('expense_date',{ascending:false}),supabase.from('incomes').select('*,categories(name)').eq('family_id',id).order('income_date',{ascending:false}),supabase.from('settlements').select('*').eq('family_id',id).order('created_at',{ascending:false})]);setMembers(m.data||[]);setCats(c.data||[]);setExpenses(e.data||[]);setIncome(i.data||[]);setSettlements(s.data||[]);const active=(m.data||[]).filter(x=>x.is_active);if(active.length)setForm((x:any)=>({...x,payer:x.payer||active[0].id,members:x.members.length?x.members:[active[0].id]}));if(c.data?.length)setForm((x:any)=>({...x,category:x.category||c.data.find((z:any)=>z.kind==='expense')?.id||''}));localStorage.setItem('ledgerly_family_id',id);setBusy(false)}
 async function login(e:any){e.preventDefault();const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});setNotice(error?.message||'Magic link sent.');}
 async function createFamily(e:any){e.preventDefault();const {data,error}=await supabase.rpc('create_family',{p_name:familyForm.name,p_pin:familyForm.pin});if(error)return setNotice(error.message);const r=data?.[0];if(r){const f={id:r.family_id,name:r.family_name,family_code:r.family_code};setFamily(f);setFamilies(x=>[...x,f]);setFamilyMode('choose')}}
 async function joinFamily(e:any){e.preventDefault();const {data,error}=await supabase.rpc('join_family',{p_code:familyForm.code.trim().toUpperCase(),p_pin:familyForm.pin,p_name:familyForm.memberName});if(error)return setNotice(error.message);await loadFamilies();if(data?.[0]?.family_id){const {data:f}=await supabase.from('families').select('*').eq('id',data[0].family_id).single();if(f)setFamily(f)}}
 async function saveExpense(e:any){e.preventDefault();if(!family||!session)return;const amount=Number(form.amount);const ids=form.split==='single'?[form.payer]:form.members;if(!(amount>0)||!form.description||!form.payer||!ids.length)return setNotice('Amount, description, payer and responsibility are required.');const alloc=form.split==='equal'?splitEqual(amount,ids):[{member_id:ids[0],amount:Number(amount.toFixed(2))}];if(form.split!=='single'&&form.split!=='equal')return setNotice('Choose single or equal split for this first release.');setBusy(true);const {data,error}=await supabase.from('expenses').insert({family_id:family.id,category_id:form.category||null,description:form.description.trim(),amount,expense_date:form.date,expense_type:form.type,payment_method:form.payment,created_by:session.user.id}).select().single();if(error){setNotice(error.message);setBusy(false);return}await supabase.from('expense_payers').insert({expense_id:data.id,member_id:form.payer,amount});await supabase.from('expense_allocations').insert(alloc.map((a:any)=>({...a,expense_id:data.id})));setForm((x:any)=>({...x,description:'',amount:'',date:today()}));setNotice('Expense saved.');setScreen('expenses');await loadFamily(family.id);setBusy(false)}
 async function settle(s:any){const {error}=await supabase.from('settlements').insert({family_id:family.id,from_member_id:s.from,to_member_id:s.to,amount:s.amount,paid_amount:s.amount,status:'paid',settled_at:new Date().toISOString()});setNotice(error?.message||'Settlement recorded.');if(!error)loadFamily(family.id)}
 async function addMember(e:any){e.preventDefault();const name=e.currentTarget.name.value;const {error}=await supabase.from('family_members').insert({family_id:family.id,name,is_active:true});setNotice(error?.message||'Member added.');if(!error)loadFamily(family.id)}
 async function signOut(){await supabase.auth.signOut();setSession(null);setFamily(null)}
 const active=expenses.filter(e=>!e.deleted_at);const filtered=active.filter(e=>month(e.expense_date)===filter&&(!search||`${e.description} ${e.categories?.name||''}`.toLowerCase().includes(search.toLowerCase())));const bs=balances(active,settlements,members);const suggestions=settleSuggestions(bs);const spend=active.filter(e=>month(e.expense_date)===filter).reduce((s,e)=>s+Number(e.amount),0);const inc=income.filter(i=>month(i.income_date)===filter).reduce((s,i)=>s+Number(i.amount),0);const memberName=(id:string)=>members.find(m=>m.id===id)?.name||'Unknown';
 if(!session)return <main className="auth"><div className="authCard"><div className="brand"><span className="logo">L</span><div><b>Ledgerly</b><small>Family money, clearly.</small></div></div><h1>Shared expenses without the confusion.</h1><p>Track who paid, who is responsible, and exactly who owes whom.</p><form onSubmit={login}><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="btn primary full">Send magic link</button></form>{notice&&<div className="notice">{notice}</div>}</div></main>;
 if(!family)return <main className="auth"><div className="authCard wide"><div className="brand"><span className="logo">L</span><div><b>Ledgerly</b><small>Family setup</small></div></div>{familyMode==='choose'?<><h1>Set up your family space.</h1><p>Create a private family ledger or join an existing one.</p><div className="choiceGrid"><button className="choice" onClick={()=>setFamilyMode('create')}><b>Create family</b><span>Start a new shared ledger.</span></button><button className="choice" onClick={()=>setFamilyMode('join')}><b>Join family</b><span>Use your family code and PIN.</span></button></div></>:<form onSubmit={familyMode==='create'?createFamily:joinFamily}><button type="button" className="back" onClick={()=>setFamilyMode('choose')}>← Back</button>{familyMode==='create'?<><h2>Create family</h2><label>Family name<input required value={familyForm.name} onChange={e=>setFamilyForm({...familyForm,name:e.target.value})}/></label><label>PIN<input required pattern="[0-9]{4,6}" value={familyForm.pin} onChange={e=>setFamilyForm({...familyForm,pin:e.target.value})}/></label><button className="btn primary full">Create family</button></>:<><h2>Join family</h2><label>Code<input required value={familyForm.code} onChange={e=>setFamilyForm({...familyForm,code:e.target.value.toUpperCase()})}/></label><label>PIN<input required value={familyForm.pin} onChange={e=>setFamilyForm({...familyForm,pin:e.target.value})}/></label><label>Your name<input required value={familyForm.memberName} onChange={e=>setFamilyForm({...familyForm,memberName:e.target.value})}/></label><button className="btn primary full">Join family</button></>}</form>}{notice&&<div className="notice">{notice}</div>}<button className="linkBtn" onClick={signOut}>Sign out</button></div></main>;
 return <main className="app"><header className="topbar"><div className="brand"><span className="logo">L</span><div><b>Ledgerly</b><small>{family.name}</small></div></div><div className="topActions"><span className="code">{family.family_code}</span><button className="iconBtn" onClick={()=>setDark(!dark)}>{dark?'☀':'☾'}</button><button className="iconBtn" onClick={signOut}>↪</button></div></header><section className="content">{notice&&<div className="notice toast">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 {screen==='home'&&<><div className="hero"><div><span className="eyebrow">{filter}</span><h1>Family money, under control.</h1><p>See spending, income and who owes whom.</p></div><button className="btn primary" onClick={()=>setScreen('add')}>＋ Add expense</button></div><div className="stats"><div><span>Spent</span><b>{money(spend)}</b></div><div><span>Income</span><b className="good">{money(inc)}</b></div><div><span>Savings</span><b>{money(inc-spend)}</b></div><div><span>Outstanding</span><b className={suggestions.length?'warn':''}>{money(suggestions.reduce((s,x)=>s+x.amount,0))}</b></div></div><div className="grid2"><div className="card"><h3>Who owes whom</h3>{suggestions.slice(0,5).map(s=><div className="owe" key={s.from+s.to}><span>{s.fromName} owes {s.toName}</span><strong>{money(s.amount)}</strong></div>)}{!suggestions.length&&<div className="successBox">Everyone is settled up 🎉</div>}</div><div className="card"><h3>Member balances</h3>{bs.map(m=><div className="balanceRow" key={m.id}><div className="avatar">{m.name[0]}</div><div className="grow"><b>{m.name}</b><small>Net position</small></div><strong className={m.balance>=0?'good':'warn'}>{money(m.balance)}</strong></div>)}</div></div></>}
 {screen==='add'&&<div className="card pageCard"><div className="pageTitle"><div><span className="eyebrow">Quick entry</span><h1>Add expense</h1></div><button className="btn" onClick={()=>setScreen('home')}>Cancel</button></div><form className="formGrid" onSubmit={saveExpense}><label>Description*<input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Amount*<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{cats.filter(c=>c.kind==='expense').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Paid by<select value={form.payer} onChange={e=>setForm({...form,payer:e.target.value})}>{members.filter(m=>m.is_active).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{TYPES.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label>Payment<select value={form.payment} onChange={e=>setForm({...form,payment:e.target.value})}>{PAYMENTS.map(x=><option key={x}>{x}</option>)}</select></label><div className="span2"><span className="label">Responsibility</span><div className="chips"><button type="button" className={form.split==='single'?'chip selected':'chip'} onClick={()=>setForm({...form,split:'single',members:[form.payer]})}>One person</button><button type="button" className={form.split==='equal'?'chip selected':'chip'} onClick={()=>setForm({...form,split:'equal'})}>Split equally</button></div>{form.split==='equal'&&<div className="memberChecks" style={{marginTop:12}}>{members.filter(m=>m.is_active).map(m=><label key={m.id}><input type="checkbox" checked={form.members.includes(m.id)} onChange={e=>setForm((x:any)=>({...x,members:e.target.checked?[...x.members,m.id]:x.members.filter((id:string)=>id!==m.id)}))}/>{m.name}</label>)}</div>}</div><button className="btn primary">Save expense</button></form></div>}
 {screen==='expenses'&&<div className="card pageCard"><div className="pageTitle"><div><span className="eyebrow">Ledger</span><h1>Expenses</h1></div><button className="btn primary" onClick={()=>setScreen('add')}>＋ Add</button></div><div className="filters"><input placeholder="Search expenses" value={search} onChange={e=>setSearch(e.target.value)}/><input type="month" value={filter} onChange={e=>setFilter(e.target.value)}/></div>{filtered.map(e=><div className="expenseRow" key={e.id}><div className="categoryIcon">₹</div><div className="grow"><b>{e.description}</b><small>{e.expense_date} · {e.categories?.name||'Other'} · Paid by {memberName(e.expense_payers?.[0]?.member_id)}</small><small>{(e.expense_allocations||[]).map((a:any)=>`${memberName(a.member_id)} ${money(a.amount)}`).join(' · ')}</small></div><strong>{money(e.amount)}</strong></div>)}</div>}
 {screen==='settlements'&&<div className="card pageCard"><div className="pageTitle"><div><span className="eyebrow">Settlement</span><h1>Who owes whom</h1></div></div>{suggestions.map(s=><div className="settleCard" key={s.from+s.to}><div><b>{s.fromName} → {s.toName}</b><small>Suggested transfer to settle the net balance.</small></div><strong>{money(s.amount)}</strong><button className="btn primary" onClick={()=>settle(s)}>Mark paid</button></div>)}{!suggestions.length&&<div className="successBox">No outstanding settlement.</div>}<h3>Balances</h3>{bs.map(m=><div className="summaryLine" key={m.id}><span>{m.name}</span><b className={m.balance>=0?'good':'warn'}>{money(m.balance)}</b></div>)}</div>}
 {screen==='family'&&<div className="grid2"><div className="card pageCard"><span className="eyebrow">Shared space</span><h1>{family.name}</h1><div className="codeCard"><span>Family code</span><strong>{family.family_code}</strong><small>Share this code and PIN privately.</small></div><form onSubmit={addMember} className="inlineForm"><input name="name" required placeholder="Member name"/><button className="btn primary">Add member</button></form>{members.map(m=><div className="balanceRow" key={m.id}><div className="avatar">{m.name[0]}</div><div className="grow"><b>{m.name}</b><small>{m.email||'Family member'}</small></div></div>)}</div><div className="card pageCard"><h3>Families</h3>{families.map(f=><button className="familyOption" key={f.id} onClick={()=>setFamily(f)}><b>{f.name}</b><small>{f.family_code}</small></button>)}</div></div>}
 </section><nav className="bottomNav">{[['home','Home','⌂'],['expenses','Ledger','▤'],['add','Add','＋'],['settlements','Settle','↔'],['family','Family','♙']].map(([id,label,icon])=><button key={id} className={screen===id?'active':''} onClick={()=>setScreen(id)}><span>{icon}</span>{label}</button>)}</nav>{busy&&<div className="loading">Working…</div>}</main>;
}