from pathlib import Path

path = Path('app/page.tsx')
s = path.read_text(encoding='utf-8')
replacements = [
    ("const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);", "const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:2,maximumFractionDigits:2}).format(n||0);"),
    ("expense_allocations(member_id,amount),categories(name)", "expense_allocations(member_id,amount,percentage),categories(name)"),
    ("notes:expense.notes||null,updated_by:session.user.id,deleted_at:null", "notes:expense.notes||null,split_mode:expense.split,updated_by:session.user.id,deleted_at:null"),
    ("expense_type:expense.type,payment_method:expense.payment,notes:expense.notes||null,created_by:session.user.id", "expense_type:expense.type,payment_method:expense.payment,notes:expense.notes||null,split_mode:expense.split,created_by:session.user.id"),
    (" async function editExpense(e:any){setEditingId(e.id);setExpense({description:e.description,amount:String(e.amount),date:e.expense_date,payer:e.expense_payers?.[0]?.member_id||'',category:e.category_id||'',type:e.expense_type,payment:e.payment_method||'UPI',notes:e.notes||'',split:e.expense_allocations?.length>1?'equal':'single',members:(e.expense_allocations||[]).map((a:{member_id:string})=>a.member_id),custom:{},percent:{},search:expense.search});setScreen('add')}", " async function editExpense(e:any){const allocations=e.expense_allocations||[];const mode=e.split_mode|| (allocations.length>1?'equal':'single');const custom=mode==='custom'?Object.fromEntries(allocations.map((a:any)=>[a.member_id,String(a.amount)])):{};const percent=mode==='percentage'?Object.fromEntries(allocations.map((a:any)=>[a.member_id,String(a.percentage??0)])):{};setEditingId(e.id);setExpense({description:e.description,amount:String(e.amount),date:e.expense_date,payer:e.expense_payers?.[0]?.member_id||'',category:e.category_id||'',type:e.expense_type,payment:e.payment_method||'UPI',notes:e.notes||'',split:mode,members:allocations.map((a:any)=>a.member_id),custom,percent,search:expense.search});setScreen('add')}")
]
for old, new in replacements:
    if old not in s:
        raise SystemExit(f'Expected source fragment not found: {old[:100]}')
    s = s.replace(old, new, 1)

old_calc = "const calc=useMemo(()=>{const liveExpenses=expenses.filter((e:any)=>!e.deleted_at);const monthKey=new Date().toISOString().slice(0,7),monthExpenses=liveExpenses.filter((e:any)=>String(e.expense_date).slice(0,7)===monthKey);const total=monthExpenses.reduce((s:any,e:any)=>s+Number(e.amount),0),incomeTotal=incomes.filter((i:any)=>String(i.income_date).slice(0,7)===monthKey).reduce((s:any,e:any)=>s+Number(e.amount),0);const byCat:any={},byType:any={};monthExpenses.forEach((e:any)=>{const k=e.categories?.name||'Uncategorised';byCat[k]=(byCat[k]||0)+Number(e.amount);byType[e.expense_type]=(byType[e.expense_type]||0)+Number(e.amount)});const balances=members.map((m:any)=>{const paid=liveExpenses.reduce((s:any,e:any)=>s+(e.expense_payers||[]).filter((p:any)=>p.member_id===m.id).reduce((a:any,p:any)=>a+Number(p.amount),0),0);const own=liveExpenses.reduce((s:any,e:any)=>s+(e.expense_allocations||[]).filter((a:any)=>a.member_id===m.id).reduce((a:any,p:any)=>a+Number(p.amount),0),0);const settledOut=settlements.filter((s:any)=>s.status!=='reversed'&&s.from_member_id===m.id).reduce((a:any,s:any)=>a+Number(s.paid_amount||0),0);const settledIn=settlements.filter((s:any)=>s.status!=='reversed'&&s.to_member_id===m.id).reduce((a:any,s:any)=>a+Number(s.paid_amount||0),0);return {...m,paid,own,net:paid-own+settledOut-settledIn}});return{total,incomeTotal,savings:incomeTotal-total,byCat,byType,balances}},[expenses,incomes,members,settlements]);"
new_calc = "const calc=useMemo(()=>{const liveExpenses=expenses.filter((e:any)=>!e.deleted_at);const monthKey=new Date().toISOString().slice(0,7),monthExpenses=liveExpenses.filter((e:any)=>String(e.expense_date).slice(0,7)===monthKey);const total=monthExpenses.reduce((s:any,e:any)=>s+Number(e.amount),0),incomeTotal=incomes.filter((i:any)=>String(i.income_date).slice(0,7)===monthKey).reduce((s:any,e:any)=>s+Number(e.amount),0);const byCat:any={},byType:any={};monthExpenses.forEach((e:any)=>{const k=e.categories?.name||'Uncategorised';byCat[k]=(byCat[k]||0)+Number(e.amount);byType[e.expense_type]=(byType[e.expense_type]||0)+Number(e.amount)});const balances=members.map((m:any)=>{const paid=liveExpenses.reduce((s:any,e:any)=>s+(e.expense_payers||[]).filter((p:any)=>p.member_id===m.id).reduce((a:any,p:any)=>a+Number(p.amount),0),0);const own=liveExpenses.reduce((s:any,e:any)=>s+(e.expense_allocations||[]).filter((a:any)=>a.member_id===m.id).reduce((a:any,p:any)=>a+Number(p.amount),0),0);const settledOut=settlements.filter((s:any)=>s.status!=='reversed'&&s.from_member_id===m.id).reduce((a:any,s:any)=>a+Number(s.paid_amount||0),0);const settledIn=settlements.filter((s:any)=>s.status!=='reversed'&&s.to_member_id===m.id).reduce((a:any,s:any)=>a+Number(s.paid_amount||0),0);const transferOut=transfers.filter((t:any)=>t.from_member_id===m.id).reduce((a:any,t:any)=>a+Number(t.amount||0),0);const transferIn=transfers.filter((t:any)=>t.to_member_id===m.id).reduce((a:any,t:any)=>a+Number(t.amount||0),0);const loanReceivable=loans.filter((l:any)=>l.from_member_id===m.id&&l.status!=='closed').reduce((a:any,l:any)=>a+Number(l.outstanding??l.principal??0),0);const loanPayable=loans.filter((l:any)=>l.to_member_id===m.id&&l.status!=='closed').reduce((a:any,l:any)=>a+Number(l.outstanding??l.principal??0),0);return {...m,paid,own,net:paid-own+settledOut-settledIn+transferOut-transferIn+loanReceivable-loanPayable}});return{total,incomeTotal,savings:incomeTotal-total,byCat,byType,balances}},[expenses,incomes,members,settlements,transfers,loans]);"
if old_calc not in s:
    raise SystemExit('Expected calc source fragment not found')
s=s.replace(old_calc,new_calc,1)

old_note='<h3>Family transfer</h3><form className="expenseForm"'
new_note='<h3>Family transfer</h3><p className="muted">Transfers and loans affect settlement balances: the sender/lender receives credit and the receiver/borrower carries the obligation.</p><form className="expenseForm"'
if old_note not in s:
    raise SystemExit('Expected transfer UI fragment not found')
s=s.replace(old_note,new_note,1)

path.write_text(s,encoding='utf-8')
print('Phase 1 applied')
